name: notificare_push_lib
description: Official Notificare Flutter plugin. Implements the power of the Notificare platform in Flutter applications.
version: 2.7.0
homepage: https://notificare.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
  flutter_plugin_android_lifecycle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  json_serializable: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: re.notifica.flutter
        pluginClass: NotificarePushLibPlugin
      ios:
        pluginClass: NotificarePushLibPlugin
